#!/bin/bash -efux

source $(dirname "${BASH_SOURCE[0]}")/config.sh

PATH=$OPENSSL_INSTALL_PREFIX/bin:$PATH
BUILD_ENGINE=${GOST_BUILD_ENGINE:+-DGOST_BUILD_ENGINE=$GOST_BUILD_ENGINE}
BUILD_PROVIDER=${GOST_BUILD_PROVIDER:+-DGOST_BUILD_PROVIDER=$GOST_BUILD_PROVIDER}

mkdir -p build
cd build
cmake -DTLS13_PATCHED_OPENSSL=$PATCH_OPENSSL -DOPENSSL_ROOT_DIR=$OPENSSL_INSTALL_PREFIX \
    -DOPENSSL_ENGINES_DIR=$OPENSSL_INSTALL_PREFIX/engines ${ASAN-} \
    $BUILD_ENGINE $BUILD_PROVIDER ..
make
make test CTEST_OUTPUT_ON_FAILURE=1
if [ -z "${ASAN-}" ]; then
    make tcl_tests
fi
