name: CI
on:
    push:
    pull_request:
    schedule:
        - cron: '0 2 * * 0'

env:
    OPENSSL_BRANCH: openssl-3.6.0
    USE_RPATH: yes
    PATCH_OPENSSL: 0
    GOST_PROVIDER_ENABLE_ONLINE_TESTS: 1
    GOST_ENABLE_LEGACY: ON

jobs:
    gcc-openssl-stable:
        runs-on: ubuntu-latest
        env:
            PATCH_OPENSSL: 1
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: true
            - run: .github/before-script.sh
            - run: .github/build-engine.sh

    clang-openssl-stable:
        runs-on: ubuntu-latest
        env:
            CC: clang
            PATCH_OPENSSL: 1
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: true
            - run: .github/before-script.sh
            - run: .github/build-engine.sh

    macos-openssl-stable:
        runs-on: macos-latest
        env:
            USE_RPATH:
            PATCH_OPENSSL: 1
            GOST_PROVIDER_ENABLE_ONLINE_TESTS: 0 # macOS runner has no network access to infotecs TLS1.3 server
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: true
            - run: .github/before-script.sh
            - run: .github/build-engine.sh

    gcc-openssl-master:
        runs-on: ubuntu-latest
        env:
            OPENSSL_BRANCH: master
            GOST_ENABLE_LEGACY: OFF
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: true
            - run: .github/before-script.sh
            - run: .github/build-engine.sh

    clang-openssl-master:
        runs-on: ubuntu-latest
        env:
            CC: clang
            OPENSSL_BRANCH: master
            GOST_ENABLE_LEGACY: OFF
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: true
            - run: .github/before-script.sh
            - run: .github/build-engine.sh

    macos-openssl-master:
        runs-on: macos-latest
        env:
            OPENSSL_BRANCH: master
            GOST_ENABLE_LEGACY: OFF
            USE_RPATH:
            GOST_PROVIDER_ENABLE_ONLINE_TESTS: 0 # macOS runner has no network access to infotecs TLS1.3 server
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: true
            - run: .github/before-script.sh
            - run: .github/build-engine.sh

    gcc-asan-openssl-master:
        runs-on: ubuntu-latest
        env:
            OPENSSL_BRANCH: master
            GOST_ENABLE_LEGACY: OFF
            ASAN: -DASAN=1
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: true
            - run: .github/before-script.sh
            - run: .github/build-engine.sh

    macos-asan-openssl-master:
        runs-on: macos-latest
        env:
            OPENSSL_BRANCH: master
            GOST_ENABLE_LEGACY: OFF
            ASAN: -DASAN=1
            USE_RPATH:
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: true
            - run: .github/before-script.sh
            - run: .github/build-engine.sh

    gcc-openssl-stable-x86:
       runs-on: ubuntu-latest
       env:
           cflags: -m32
           ldflags: -m32
           setarch: "setarch i386"
           apt_install: gcc-multilib
           patch_openssl: 1
       steps:
           - uses: actions/checkout@v2
             with:
                 submodules: true
           - run: .github/before-script.sh
           - run: .github/build-engine.sh